### PR TITLE
Made the charset tag take effect propperly.

### PR DESCRIPTION
**Pull request by trypsynth**
The charset tag was <meta charset='UTF-8>, not <meta charset='utf-8'> I've fixed this.

### CODE REVIEW

**Comment by trypsynth** [comment]
Okay, I've also formatted and moved the readme stuff.

**Comment by amerikrainian** [comment]
Appreciate the contribution.

**Comment by amerikrainian** [comment]
@TheQuinbox Please reopen a request while including the CNAME file. Also feel free to edit the readme to make note of this. CNAME is what keeps the domain and the website linked so going to github.io version would redirect you to the audiogamerecordings.com. I merged before I realized and I think you must open a new one because there is no way to unlock the request on my end.

**Comment by trypsynth** [comment]
Okay, will do. What's supposed to go in that file? It didn't exist when I forked.

**Pull request merged**
